Hello,

This is an automated e-mail message requesting a prefix list modification 
from providers who still build their prefix filters manually, rather than 
from the Internet Routing Registry (IRR) databases.

A list of requested changes is contained below, followed by a complete 
list of prefixes for your reference. Please update the prefix-lists for 
all BGP sessions with our ASN. Also please note that the prefixes are 
pre-aggregated, and should always be applied with at least "upto /24" 
(Juniper) or "le 24" (Cisco).

Thank you for your time.
